//! Procedural macros for relay.
//!
//! Currently provides `#[derive(Reactive)]` which transforms a plain struct
//! into one where every field is wrapped in `Signal<T>`, with generated
//! accessor methods. This enables field-level reactivity without the caller
//! manually creating individual signals.

use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{Data, DeriveInput, Fields, parse_macro_input};

/// Derive reactive field-level accessors for a struct.
///
/// Each field is wrapped in `Signal<T>` internally. Generated methods:
/// - `ReactiveFoo::new(cx, field1, field2, ...)` — constructor
/// - `foo.get_name(cx) -> T` — read with dependency tracking (requires `T: Clone`)
/// - `foo.set_name(cx, value)` — write and notify (requires `T: PartialEq`)
/// - `foo.update_name(cx, |t| { ...; bool })` — in-place mutation
/// - `foo.signal_name() -> &Signal<T>` — direct signal access
///
/// # Example
///
/// ```ignore
/// #[derive(Reactive)]
/// struct Counter {
///     count: i32,
///     label: String,
/// }
///
/// let counter = Counter::new(cx, 0, "Hello".into());
/// counter.set_count(cx, 5);
/// let label = counter.get_label(cx);
/// ```
#[proc_macro_derive(Reactive)]
pub fn derive_reactive(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let name = &input.ident;
    let reactive_name = format_ident!("Reactive{}", name);

    let fields = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(fields) => &fields.named,
            Fields::Unnamed(_) => {
                return syn::Error::new_spanned(
                    &input,
                    "Reactive derive only supports named fields",
                )
                .to_compile_error()
                .into();
            }
            Fields::Unit => {
                return syn::Error::new_spanned(
                    &input,
                    "Reactive derive requires at least one field",
                )
                .to_compile_error()
                .into();
            }
        },
        _ => {
            return syn::Error::new_spanned(&input, "Reactive derive only supports structs")
                .to_compile_error()
                .into();
        }
    };

    let field_names: Vec<_> = fields.iter().filter_map(|f| f.ident.as_ref()).collect();
    let field_types: Vec<_> = fields.iter().map(|f| &f.ty).collect();

    // Generate the wrapper struct with Signal<T> fields.
    let signal_fields = field_names.iter().zip(field_types.iter()).map(|(fname, ftype)| {
        quote! { #fname: relay::Signal<#ftype> }
    });

    // Generate the constructor parameters and signal creation.
    let ctor_params = field_names.iter().zip(field_types.iter()).map(|(fname, ftype)| {
        quote! { #fname: #ftype }
    });
    let ctor_body = field_names.iter().map(|fname| {
        quote! { #fname: relay::Signal::new(cx, #fname) }
    });

    // Generate accessor methods for each field.
    let accessors = field_names.iter().zip(field_types.iter()).map(|(fname, ftype)| {
        let get_method = format_ident!("get_{}", fname);
        let set_method = format_ident!("set_{}", fname);
        let update_method = format_ident!("update_{}", fname);
        let signal_method = format_ident!("signal_{}", fname);

        quote! {
            /// Read the field value with dependency tracking (requires `T: Clone`).
            pub fn #get_method(&self, cx: &gpui::App) -> #ftype
            where #ftype: Clone
            {
                self.#fname.get(cx)
            }

            /// Write the field value and notify dependents (requires `T: PartialEq`).
            pub fn #set_method(&self, cx: &mut gpui::App, value: #ftype)
            where #ftype: PartialEq
            {
                self.#fname.set(cx, value);
            }

            /// Mutate the field in place. The closure returns whether
            /// dependents should be notified.
            pub fn #update_method(&self, cx: &mut gpui::App, update: impl FnOnce(&mut #ftype) -> bool) {
                self.#fname.update(cx, update);
            }

            /// Direct access to the underlying signal.
            pub fn #signal_method(&self) -> &relay::Signal<#ftype> {
                &self.#fname
            }
        }
    });

    let expanded = quote! {
        /// Reactive wrapper generated by `#[derive(Reactive)]`.
        ///
        /// Each field is wrapped in `Signal<T>` for field-level dependency
        /// tracking — changing one field only notifies consumers of that
        /// specific field, not the entire struct.
        pub struct #reactive_name {
            #(#signal_fields,)*
        }

        impl #reactive_name {
            /// Create a new reactive struct, wrapping each field value in a
            /// `Signal<T>`.
            pub fn new(cx: &mut gpui::App, #(#ctor_params,)*) -> Self {
                Self {
                    #(#ctor_body,)*
                }
            }

            #(#accessors)*
        }
    };

    expanded.into()
}
